networks:
  lendmate-net:
    external: true

services:
  order-service:
    image: "order-service"
    build: .
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_service_db_dev
      SPRING_DATASOURCE_USERNAME: lendmate
      SPRING_DATASOURCE_PASSWORD: lendmate
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
    networks:
      - lendmate-net

volumes:
  postgres_data: