networks:
  lendmate-net:
    external: true

services:
  order-service:
    image: "order-service"
    build: .
    container_name: order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_service_db
      SPRING_DATASOURCE_USERNAME: lendmate
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xmx150m -Xms96m"
    restart: unless-stopped
    networks:
      - lendmate-net

volumes:
  postgres_data: